### ISSUE TITLE
MIPT Dataset

### ISSUE THREAD

**Issue by Mingqj** [theitzin/FUS3D#1]
Hi, I am very interested in your work!
But I am confused: is the MIPT dataset open source, and where can I download this dataset?
Thanks in advance!

**Comment by theitzin** [comment]
Hi! Thank you for your interest in our work. You can download the MIPT dataset [here](https://zenodo.org/records/5592323).
If you are mainly interested in multimodal data rather than the 3D annotation we can also recommend our [TRISTAR dataset](https://zenodo.org/records/7996570), which is larger and has registered RGB/depth and thermal channels. It is however instead labeled for segmentation and action recognition.

**Comment by Mingqj** [comment]
> Hi! Thank you for your interest in our work. You can download the MIPT dataset [here](https://zenodo.org/records/5592323). If you are mainly interested in multimodal data rather than the 3D annotation we can also recommend our [TRISTAR dataset](https://zenodo.org/records/7996570), which is larger and has registered RGB/depth and thermal channels. It is however instead labeled for segmentation and action recognition.

Thank you for your reply! My study mainly focuses on 3D object detection, and there are many aspects of your work that I can learn from. It is my pleasure to communicate with you! :smile:
